# Stage 1: Build the application
FROM node:20-alpine AS builder

WORKDIR /app

# Copiar los archivos necesarios
COPY package.json pnpm-lock.yaml ./
RUN npm install -g pnpm && pnpm install --frozen-lockfile

COPY . .

# Usar variables de entorno en la construcción
ARG NODE_ENV
ARG DATABASE_URL
ARG SHADOW_DATABASE_URL
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG NEXTAUTH_URL
ARG RESEND_API_KEY
ARG NEXT_PUBLIC_BANK_ACCOUNT
ARG NEXT_PUBLIC_BANK_NAME
ARG NEXT_PUBLIC_COMPANY_NAME
ARG BASE_URL
ARG API_VERSION
ARG NEXT_PUBLIC_API_VERSION
ARG BASE_API_URL
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_STORAGE_PAYMENT_URL

# Establecer las variables como variables de entorno
ENV NODE_ENV=${NODE_ENV}
ENV DATABASE_URL=${DATABASE_URL}
ENV SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
ENV GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ENV GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
ENV NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
ENV NEXTAUTH_URL=${NEXTAUTH_URL}
ENV RESEND_API_KEY=${RESEND_API_KEY}
ENV NEXT_PUBLIC_BANK_ACCOUNT=${NEXT_PUBLIC_BANK_ACCOUNT}
ENV NEXT_PUBLIC_BANK_NAME=${NEXT_PUBLIC_BANK_NAME}
ENV NEXT_PUBLIC_COMPANY_NAME=${NEXT_PUBLIC_COMPANY_NAME}
ENV BASE_URL=${BASE_URL}
ENV API_VERSION=${API_VERSION}
ENV NEXT_PUBLIC_API_VERSION=${NEXT_PUBLIC_API_VERSION}
ENV BASE_API_URL=${BASE_API_URL}
ENV NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
ENV NEXT_PUBLIC_STORAGE_PAYMENT_URL=${NEXT_PUBLIC_STORAGE_PAYMENT_URL}


RUN pnpm build

# Stage 2: Serve the application
FROM node:20-alpine

WORKDIR /app
RUN npm install -g pnpm
COPY --from=builder /app /app

EXPOSE 3000
CMD ["pnpm", "start"]
